### PR TITLE
Fix to render panels and follow the selected timezone from URL query if specified.

### PR DESCRIPTION
**Pull request by Bujupah**
Related to issue #223 

Fixing the rendered panel timezone with a custom TZ from URL query.

Need someone to produce that and check if timezone is failing too, if so review this PR and check it too. this has fixed my issue.

### CODE REVIEW

**Comment by Bujupah** [comment]
Followed this issue in puppeteer repo
https://github.com/puppeteer/puppeteer/issues/3325

**Comment by AgnesToulet** [comment]
Thanks for this PR! I did some tests and ran into the same issue. This PR fixes it but I have a few comments:
- Setting the env variable in the LaunchOptions seems to not have any effect so it may be best to remove the code from the `getLauncherOptions` and move it into a separate function like this: 
```
  async setTimezone(page, options) {
    const timezone = options.timezone || this.config.timezone;
    if (timezone) {
      await page.emulateTimezone(timezone);
    }
  }
```
@marefr WDYT? Do you know if it used to work?
- It also needs to be added in the new `renderCSV` function to be complete.

**Comment by Bujupah** [comment]
yes! It kinda needs some refactoring tbh

**Comment by marefr** [comment]
> Setting the env variable in the LaunchOptions seems to not have any effect so it may be best to remove the code from the getLauncherOptions and move it into a separate function like this:

I'm pretty sure it did work back in the days. But if this works all is good 👍

**Comment by Bujupah** [comment]
> Thanks for this PR! I did some tests and ran into the same issue. This PR fixes it but I have a few comments:
> 
> * Setting the env variable in the LaunchOptions seems to not have any effect so it may be best to remove the code from the `getLauncherOptions` and move it into a separate function like this:
> 
> ```
>   async setTimezone(page, options) {
>     const timezone = options.timezone || this.config.timezone;
>     if (timezone) {
>       await page.emulateTimezone(timezone);
>     }
>   }
> ```
> 
> @marefr WDYT? Do you know if it used to work?
> 
> * It also needs to be added in the new `renderCSV` function to be complete.

I updated my PR with this function

**Comment by AgnesToulet** [comment]
Sorry for the delay, thanks for the update! Could you also add it to the [`renderCSV`](https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts#L233) function please to have the same behavior? 

And also, could you merge with master to fix the issues with the pipeline? Thanks!

**Comment by Bujupah** [comment]
Thanks @AgnesToulet
I made that change

**Review by AgnesToulet — APPROVED** [review]

**Pull request merged**
