### PR TITLE
Update documentation for rendering modes and performance

### PR DESCRIPTION
**Pull request by AgnesToulet**

### CODE REVIEW

**Comment by mjseaman** [comment]
Thanks for this @AgnesToulet. I think it would be valuable to create a Readme section specifically for performance optimization, with tips for making it performant.

Also - is there image renderer documentation in the official Grafana docs?

**Comment by mjseaman** [comment]
CC @pianohacker for visibility

**Comment by mjseaman** [comment]
> Thanks for this @AgnesToulet. I think it would be valuable to create a Readme section specifically for performance optimization, with tips for making it performant.
> 
> Also - is there image renderer documentation in the official Grafana docs?

Looks like there is indeed [a Grafana docs section specifically focused on the image renderer](https://grafana.com/docs/grafana/latest/administration/image_rendering/). @osg-grafana , this looks like a good cross-functional project with @AgnesToulet and @pianohacker to update the docs with an installation and configuration guide for optimizing image renderer performance.

**Comment by osg-grafana** [comment]
Hi @mjseaman, Jita is the lead writer on Grafana OSS, so this is in her remit since it is indeed a Grafana OSS feature. @achatterjee-grafana, please align with the Grafana Enteprise engineers and this ProductBoard feature for deadlines: https://grafana.productboard.com/feature-board/2503125-enterprise-feature-prioritization/features/7079012/detail.

Also, for context, @pianohacker ("Hi!") is currently a new engineer who is onboarding on the Grafana Enterprise team.

**Comment by AgnesToulet** [comment]
Closing this as these changes will be in the Grafana documentation, see: https://github.com/grafana/grafana/pull/38759

**Comment by achatterjee-grafana** [comment]
> Hi @mjseaman, Jita is the lead writer on Grafana OSS, so this is in her remit since it is indeed a Grafana OSS feature. @achatterjee-grafana, please align with the Grafana Enteprise engineers and this ProductBoard feature for deadlines: https://grafana.productboard.com/feature-board/2503125-enterprise-feature-prioritization/features/7079012/detail.
> 
> Also, for context, @pianohacker ("Hi!") is currently a new engineer who is onboarding on the Grafana Enterprise team.

Thanks, @osg-grafana. Met with @AgnesToulet about this yesterday.

**Pull request closed without merging**
