### PR TITLE
Update Dockerfile to fix chromium segfault

### PR DESCRIPTION
**Pull request by mattes**
Running Chrome Headless inside a Docker container requires some more work. Currently none of the grafana-image-renderer images start for me.

```
docker run -it --rm grafana/grafana-image-renderer
Segmentation fault (core dumped)
```

Running with `--privileged` fixes it, but it's not a great solution.

```
docker run -it --rm --privileged grafana/grafana-image-renderer
HTTP Server started, listening on 8081
```

[Zenika/alpine-chrome](https://github.com/Zenika/alpine-chrome#3-ways-to-use-chrome-headless-with-this-image) mentions there is three ways to run chrome headless inside docker:

* With --no-sandbox
* With SYS_ADMIN capability
* With seccomp

But according to [Headless Chrome FAQ](https://developers.google.com/web/updates/2017/04/headless-chrome#faq):
> --no-sandbox is not needed if you properly setup a user in the container.

---

__This PR updates the Dockerfile to set up and use a `chrome` user inside the container so that the container can be started without any further security flags.__

Some more notes:
* I tried to stick with alpine first, but even after adding a user and group with (adduser/addgroup) it would still segfault.
* Buster is necessary for `fonts-open-sans`.
* I removed `udev`, I don't think it's needed.
* `ca-certificates` might actually not be needed, but it probably doesn't hurt to install.
* ENV vars are set in the correct build step now.
* The image is now 761 MB vs 536 MB before.
* I used  [lighthousebot's Dockerfile](https://github.com/GoogleChromeLabs/lighthousebot/blob/master/builder/Dockerfile) as a reference.

### CODE REVIEW

**Comment by marefr** [comment]
Thanks. No other similar reports like this. What architecture, operating system etc are you using?

**Comment by mattes** [comment]
```
$ uname -a
Linux instance-1 5.0.0-1025-gcp #26~18.04.1-Ubuntu SMP Mon Nov 11 13:09:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

This is essentially a plain Google Cloud Instance with Ubuntu Bionic running it. In case you'd like to reproduce. But yeah, I was surprised that nobody reported something before me.

**Comment by LindezaGrey** [comment]
hey @mattes ,
thanks for your investigative work! I encountered the same issue but only on my cloud machines, not on my local dev machine. I received also segfault errors which i could not explain. My "solution" was to switch to a non alpine base image (node:10 instead of node:10-alpine). But this was more of a "try until it works" solution... i might try if your solution works for me as well!

**Comment by hekmon** [comment]
Not 100% sure if related but this is the first lead I found for the issue I am having: on AWS ECS (w Fargate) the container does not start: it exists with 139 (segfault) and without any logs (captured by ECS). I tried with 1.0.5, 1.0.6 & 1.0.7.

**Comment by hekmon** [comment]
We just tested @mattes Dockerfile on ECS: it works fine :)

**Comment by aknuds1** [comment]
@marefr Should we try to test this to see if we can reproduce the error?

**Comment by marefr** [comment]
@aknuds1 would wait some more. Still very few reported this problem.

**Comment by hekmon** [comment]
@marefr you just have GCP & AWS not working ;)

You should definitely test it on your side.

On our side the env is the following:
AWS ECS/Fargate 1.3.0 (latest)

**Comment by mattes** [comment]
Related #70

**Comment by hekmon** [comment]
Thx @mattes ! I can confirm that v1.0.8-beta2 works on AWS ECS Fargate 1.3.0.

**Comment by marefr** [comment]
Thank you. Will release v1.0.8 stable soon so closing this.

**Pull request closed without merging**
