### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by River2000i**
Fix numbering and typography

### CODE REVIEW

**Comment by River2000i** [comment]
@AgnesToulet PTAL

**Review by joanlopez — APPROVED** [review]

**Comment by River2000i** [comment]
@joanlopez anyone can merge this pr?

**Comment by joanlopez** [comment]
> @joanlopez anyone can merge this pr?

Can you pull latest changes from `master` branch, please? Thanks!

**Comment by River2000i** [comment]
> Can you pull latest changes from master branch, please? Thanks!

sure ~

**Comment by joanlopez** [comment]
> > Can you pull latest changes from master branch, please? Thanks!
> 
> sure ~

Sorry, there was something wrong in the new CI settings.
Could you trigger a new build, please? (` git commit --allow-empty -m "Trigger CI"`)

**Comment by River2000i** [comment]
@joanlopez PTAL~

**Pull request merged**
