### PR TITLE
Publish multi-arch image with docker buildx

### PR DESCRIPTION
**Pull request by superbrothers**
With this PR, the grafana-image-renderer container image is published for arm64 in addition to amd64.

I've confirmed that the container image builds and publishes correctly with the following command:

```
$ read -s DOCKER_PASS; export DOCKER_PASS
$ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
$ docker buildx version
github.com/docker/buildx v0.7.1-docker 05846896d149da05f3d6fd1e7770da187b52a247
$ DOCKER_USER=superbrothers IMAGE_NAME=docker.io/superbrothers/grafana-image-renderer ./scripts/build_push_docker.sh
```

The above built image is available here. https://hub.docker.com/repository/docker/superbrothers/grafana-image-renderer

I've confirmed that the published image works fine in amd64 and arm64 environments.

```
$ uname -a
Linux nuc 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 GNU/Linux
$ sudo docker run --rm superbrothers/grafana-image-renderer:3.4.2
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
```

```
$ uname -a
Linux pi12 5.13.0-1022-raspi #24-Ubuntu SMP PREEMPT Wed Mar 16 07:19:33 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$ sudo docker run --rm superbrothers/grafana-image-renderer:3.4.2
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
```

## REF

- https://github.com/grafana/grafana-image-renderer/issues/7

### CODE REVIEW

**Comment by AaronForce1** [comment]
@Clarity-89 @joanlopez @spinillos @ArturWierzbicki 

I've verified that this should work. Aside from possibly changing the docker version to the latest supported by CircleCI (`20.10.17`) - is there anything holding us back from deploying this for ARM64 in addition to AMD64?

**Comment by rickardp** [comment]
This needs to be rebased and use Drone instead of CircleCI as it looks like the build system was changed.

Any comments from the maintainers? I'm happy to help with the rebase if needed.

**Comment by joanlopez** [comment]
> Any comments from the maintainers? I'm happy to help with the rebase if needed.

Yes, please! I'd be happy to review this once rebased and up-to-date with latest changes on `master`. 

Thanks!

**Comment by booleanbetrayal** [comment]
Would love to see this as well. Anything blocking it at this point?

**Comment by superbrothers** [comment]
Oh, sorry. I was not aware of that. I will do it this weekend.

**Comment by superbrothers** [comment]
I've just done it.

**Comment by mjgorman** [comment]
Alright, anything holding it up now? We're in the process of a Graviton migration and this is one of the few none arm64 images holding us up.

**Pull request closed without merging**
